import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { UnregisterSW } from "./UnregisterSW";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Estate Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <body className="h-full" suppressHydrationWarning>
          {process.env.NODE_ENV === "development" && <UnregisterSW />}
          <Providers>
            {process.env.NODE_ENV === "production" && <ServiceWorkerRegister />}
            {children}
            <Toaster
              position="bottom-right"
              toastOptions={{
                style: {
                  background: "rgba(20, 20, 20, 0.95)",
                  border: "1px solid rgba(255,255,255,0.1)",
                  color: "#ffffff",
                  borderRadius: "0",
                },
              }}
            />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}